<script setup>
import { computed, ref } from 'vue'
import BaseButton from '../common/BaseButton.vue'

const props = defineProps({ items: { type: Array, default: () => [] }, subtotal: { type: Number, default: 0 }, discount: { type: Number, default: 0 }, taxRate: { type: Number, default: 0.1 }, orderType: { type: String, default: 'Dine in' }, table: { type: String, default: '' }, sendingToKitchen: { type: Boolean, default: false }, allowDirectCheckout: { type: Boolean, default: true } })
const emit = defineEmits(['increment', 'decrement', 'remove', 'clear', 'checkout', 'send-to-kitchen', 'update-discount'])
const discountInput = ref('')
const tax = computed(() => Math.max(0, props.subtotal - props.discount) * props.taxRate)
const total = computed(() => Math.max(0, props.subtotal - props.discount) + tax.value)
const formatCurrency = (value) => `$${Number(value).toFixed(2)}`
function applyDiscount() { emit('update-discount', Math.min(props.subtotal, Math.max(0, Number(discountInput.value) || 0))); discountInput.value = '' }
</script>

<template>
  <aside class="flex min-h-[32rem] flex-col border-t border-border bg-surface p-5 lg:min-h-[calc(100vh-5rem)] lg:border-l lg:border-t-0 lg:p-6">
    <header class="flex items-start justify-between border-b border-border pb-4"><div><p class="text-[10px] font-bold uppercase tracking-[0.16em] text-brand">{{ orderType }}<span v-if="table"> · {{ table }}</span></p><h2 class="mt-1 text-xl font-bold text-ink">Current order</h2></div><BaseButton v-if="items.length" variant="ghost" class="min-h-8 px-2 text-xs" @click="$emit('clear')">Clear</BaseButton></header>
    <div v-if="!items.length" class="grid flex-1 place-items-center py-14 text-center"><div><span class="mx-auto grid size-12 place-items-center rounded-full bg-orange-50 text-2xl text-brand">+</span><strong class="mt-4 block text-sm text-ink">Your order is empty</strong><p class="mt-2 max-w-[13rem] text-xs leading-5 text-muted">Select a menu item to start building the order.</p></div></div>
    <ul v-else class="grid max-h-[38vh] gap-3 overflow-y-auto py-5"><li v-for="item in items" :key="item.itemKey" class="border-b border-border pb-3"><div class="flex justify-between gap-3"><div><strong class="text-sm text-ink">{{ item.name }}</strong><span v-if="item.selectedSize" class="ml-2 rounded bg-orange-50 px-1.5 py-0.5 text-[10px] font-semibold capitalize text-brand">{{ item.selectedSize }}</span><p v-if="item.modifiers?.length" class="mt-1 text-xs text-muted">{{ item.modifiers.map((modifier) => modifier.name).join(', ') }}</p><p class="mt-1 text-xs text-muted">{{ formatCurrency(item.price) }} each</p></div><strong class="text-sm text-ink">{{ formatCurrency(item.price * item.quantity) }}</strong></div><div class="mt-2 flex items-center justify-between"><div class="flex items-center gap-2 rounded-sm bg-background p-1"><button type="button" class="grid size-6 place-items-center rounded bg-surface text-ink hover:bg-brand hover:text-white" aria-label="Decrease quantity" @click="$emit('decrement', item)">-</button><span class="w-5 text-center text-xs font-semibold">{{ item.quantity }}</span><button type="button" class="grid size-6 place-items-center rounded bg-surface text-ink hover:bg-brand hover:text-white" aria-label="Increase quantity" @click="$emit('increment', item)">+</button></div><button type="button" class="text-xs text-muted hover:text-danger" @click="$emit('remove', item)">Remove</button></div></li></ul>
    <div v-if="items.length" class="mt-auto border-t border-border pt-4"><div class="mb-4 flex gap-2"><input v-model="discountInput" type="number" min="0" step="0.01" placeholder="Discount amount" class="h-9 min-w-0 flex-1 rounded-sm border border-border px-3 text-xs outline-none focus:border-brand" /><BaseButton variant="secondary" class="min-h-9 px-3 text-xs" @click="applyDiscount">Apply</BaseButton></div><div class="grid gap-2 text-sm"><div class="flex justify-between text-muted"><span>Subtotal</span><strong class="text-ink">{{ formatCurrency(subtotal) }}</strong></div><div class="flex justify-between text-muted"><span>Discount</span><strong class="text-success">-{{ formatCurrency(discount) }}</strong></div><div class="flex justify-between text-muted"><span>Tax <small>({{ (taxRate * 100).toFixed(2).replace(/\.00$/, '') }}%)</small></span><strong class="text-ink">{{ formatCurrency(tax) }}</strong></div><div class="mt-2 flex justify-between border-t border-dashed border-border pt-3 text-base font-bold text-ink"><span>Total</span><strong class="text-brand-dark">{{ formatCurrency(total) }}</strong></div></div><BaseButton class="mt-4 w-full" :disabled="sendingToKitchen" @click="$emit('send-to-kitchen')">{{ sendingToKitchen ? 'Sending to kitchen...' : 'Send to kitchen' }}</BaseButton><BaseButton v-if="allowDirectCheckout" variant="secondary" class="mt-2 w-full" @click="$emit('checkout')">Continue to payment <span aria-hidden="true">-&gt;</span></BaseButton></div>
  </aside>
</template>
